// <auto-generated />
using MagicTord_N_SondreTheWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicTord_N_SondreTheWebAPI.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230228110749_MigrationName")]
    partial class MigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.Property<int>("MovieID")
                        .HasColumnType("int");

                    b.Property<int>("CharacterID")
                        .HasColumnType("int");

                    b.HasKey("MovieID", "CharacterID");

                    b.HasIndex("CharacterID");

                    b.ToTable("CharacterMovie");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CharacterID = 1
                        },
                        new
                        {
                            MovieID = 1,
                            CharacterID = 2
                        },
                        new
                        {
                            MovieID = 2,
                            CharacterID = 3
                        },
                        new
                        {
                            MovieID = 2,
                            CharacterID = 2
                        },
                        new
                        {
                            MovieID = 3,
                            CharacterID = 4
                        },
                        new
                        {
                            MovieID = 3,
                            CharacterID = 1
                        });
                });

            modelBuilder.Entity("MagicTord_N_SondreTheWebAPI.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterID"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PictureURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("CharacterID");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterID = 1,
                            Alias = "The Cocaine Bear",
                            FullName = "Boris",
                            Gender = "Female",
                            PictureURL = "https://static01.nyt.com/images/2022/12/01/lens/01xp-cocainebear/01xp-cocainebear-mediumSquareAt3X.jpg"
                        },
                        new
                        {
                            CharacterID = 2,
                            Alias = "The Cocaine",
                            FullName = "Carol Cocaine",
                            Gender = "Female",
                            PictureURL = "https://i2-prod.chroniclelive.co.uk/incoming/article18860908.ece/ALTERNATES/s615/1_snr_nec_010920dale_01.jpg"
                        },
                        new
                        {
                            CharacterID = 3,
                            Alias = "The King",
                            FullName = "Eger Taronton",
                            Gender = "Male",
                            PictureURL = "https://i2-prod.chroniclelive.co.uk/incoming/article18860908.ece/ALTERNATES/s615/1_snr_nec_010920dale_01.jpg"
                        },
                        new
                        {
                            CharacterID = 4,
                            Alias = "Furiosa",
                            FullName = "Tharlize Cheron",
                            Gender = "Female",
                            PictureURL = "https://www.indiewire.com/wp-content/uploads/2021/05/furiosa-movie.png?w=780"
                        });
                });

            modelBuilder.Entity("MagicTord_N_SondreTheWebAPI.Models.Franchise", b =>
                {
                    b.Property<int>("FranchiseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FranchiseID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FranchiseID");

                    b.ToTable("Franchises");

                    b.HasData(
                        new
                        {
                            FranchiseID = 1,
                            Description = "The Noroff Cinematic Universe",
                            Name = "NCU"
                        },
                        new
                        {
                            FranchiseID = 2,
                            Description = "Zisson Zinematic Zeries",
                            Name = "ZZZ"
                        });
                });

            modelBuilder.Entity("MagicTord_N_SondreTheWebAPI.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieID"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FranchiseID")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PictureURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ReleaseYear")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TrailerURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("MovieID");

                    b.HasIndex("FranchiseID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Director = "Nicholas Dean Nutz",
                            FranchiseID = 1,
                            Genre = "Action/Comedy",
                            MovieTitle = "Cocain Bear",
                            PictureURL = "https://movies.universalpictures.com/media/01-cb-dm-mobile-banner-1080x745-pl-f01-112222-638e6de200084-1.jpg",
                            ReleaseYear = "2023",
                            TrailerURL = "https://www.youtube.com/watch?v=DuWEEKeJLMI"
                        },
                        new
                        {
                            MovieID = 2,
                            Director = "Nicholas Dean Nutz",
                            FranchiseID = 1,
                            Genre = "Action/Comedy",
                            MovieTitle = "Tetris",
                            PictureURL = "https://static2.tribute.ca/poster/160x236/tetris-apple-tv-167535.jpg",
                            ReleaseYear = "2023",
                            TrailerURL = "https://www.youtube.com/watch?v=-BLM1naCfME"
                        },
                        new
                        {
                            MovieID = 3,
                            Director = "Zackary Zuckerberg",
                            FranchiseID = 2,
                            Genre = "Adventure",
                            MovieTitle = "Zathura",
                            PictureURL = "https://www.themoviedb.org/t/p/original/gtlqXDVrF8E59Se2LKnBdbTw6oa.jpg",
                            ReleaseYear = "2005",
                            TrailerURL = "https://www.youtube.com/watch?v=zNxm_obDpNU"
                        });
                });

            modelBuilder.Entity("CharacterMovie", b =>
                {
                    b.HasOne("MagicTord_N_SondreTheWebAPI.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicTord_N_SondreTheWebAPI.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MagicTord_N_SondreTheWebAPI.Models.Movie", b =>
                {
                    b.HasOne("MagicTord_N_SondreTheWebAPI.Models.Franchise", null)
                        .WithMany("Movies")
                        .HasForeignKey("FranchiseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MagicTord_N_SondreTheWebAPI.Models.Franchise", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
